<template>
    <v-container>
        <h1>{{ artist.name }}</h1>
        <p>{{ artist.category }}</p>
    </v-container>

    <v-container>
        <p>{{ artist.description }}</p>
    </v-container>
</template>

<script>
    export default {
        data: () => ({
            artist: {},
            artists: [
                {
                    id: 'atlvsau',
                    name: 'ATLVS',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'beatnikcollectivemcr',
                    name: 'Beatnik Collective',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'yawnbig',
                    name: 'Big Yawn',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: '_blackbats',
                    name: 'Black Bats',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'bodyprisonau',
                    name: 'BODY PRISON',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'cerementaus',
                    name: 'Cerement',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'clownsband',
                    name: 'Clowns',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'deadskin_band',
                    name: 'DEADSKIN',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'drcolossustheband',
                    name: 'Dr. Colossus',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'drunkmums',
                    name: 'Drunk Mums',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'iamduckeye',
                    name: 'DUCKEYE',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'easybrownss',
                    name: 'Easy Browns',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'sound_exek',
                    name: 'Exek',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'future_suck',
                    name: 'Future Suck',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'g.al.ah',
                    name: 'Galah',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: '6regor',
                    name: 'Gregor',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'kosmetikamuzika_',
                    name: 'Kosmetika',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'liar.noise',
                    name: 'LIAR',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'loosetooth',
                    name: 'Loose Tooth',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'mannequindeathsquad',
                    name: 'Mannequin Death Squad',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'muma_ganoush',
                    name: 'Muma Ganoush',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'our.carlson',
                    name: 'Our Carlson',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'pollyandthepocketsband',
                    name: 'Polly and the Pockets',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'privatefunction69',
                    name: 'Private Function',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'rvgband',
                    name: 'RVG',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'sleepd93',
                    name: 'Sleep D',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'socialhaunts',
                    name: 'Social Haunts',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'thecontrollers',
                    name: 'The Controllers',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'themaggiepills',
                    name: 'The Maggie Pills',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'themiffsband',
                    name: 'The Miffs',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'theuglykings',
                    name: 'The Ugly Kings',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'timsmythholytrash',
                    name: 'Tim Smyth & HolyTrash',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'whipwerm',
                    name: 'Whipwerm',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'ynot_official_aus',
                    name: 'Ynot',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
                {
                    id: 'zenmonkee',
                    name: 'Zen Monkee',
                    category: 'Genre',
                    description: '...',
                    featuredImage: 'https://placekitten.com/500/500',
                    images: ['https://placekitten.com/500/500'],
                },
            ],
        }),

        created() {
            const ID = this.$route.params.id;
            let artist = this.artists.find((artist) => artist.id === ID);
            this.artist = artist;
        },
    }
</script>